# Generated by Django 3.2 on 2022-04-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
