# Generated by Django 3.2 on 2022-04-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_user'),
    ***REMOVED***

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ***REMOVED***
