# Generated by Django 3.2 on 2022-04-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='poster_size',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
    ]
