# Generated by Django 3.2 on 2022-04-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='cart',
        ),
    ]
