# Generated by Django 4.0.4 on 2022-05-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_usercart_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='user',
        ),
    ]
